AnyaSchool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about/', views.About.as_view(), name='about'),
    path('filter/', views.BookFilterView.as_view(), name='filter_book'),
    path('create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('books/', views.books, name='books'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
]

main/models.py
from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Book


class BookFilterForm(BSModalForm):
    type = forms.ChoiceField(choices=Book.BOOK_TYPES)

    class Meta:
        fields = ['type', 'clear']


class BookModelForm(BSModalModelForm):
    publication_date = forms.DateField(
        error_messages={'invalid': 'Enter a valid date in YYYY-MM-DD format.'}
    )

    class Meta:
        model = Book
        exclude = ['timestamp']


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

main/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)
from django.views.generic import TemplateView

from .forms import (
    BookModelForm,
    CustomUserCreationForm,
    CustomAuthenticationForm,
    BookFilterForm
)
from .models import Book


class Index(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'type' in self.request.GET:
            qs = qs.filter(book_type=int(self.request.GET['type']))
        return qs


class About(TemplateView):
    template_name = 'about.html'


class BookFilterView(BSModalFormView):
    template_name = 'examples/filter_book.html'
    form_class = BookFilterForm

    def form_valid(self, form):
        if 'clear' in self.request.POST:
            self.filter = ''
        else:
            self.filter = '?type=' + form.cleaned_data['type']

        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse_lazy('index') + self.filter


class BookCreateView(BSModalCreateView):
    template_name = 'examples/create_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('index')


class BookUpdateView(BSModalUpdateView):
    model = Book
    template_name = 'examples/update_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('index')


class BookReadView(BSModalReadView):
    model = Book
    template_name = 'examples/read_book.html'


class BookDeleteView(BSModalDeleteView):
    model = Book
    template_name = 'examples/delete_book.html'
    success_message = 'Success: Book was deleted.'
    success_url = reverse_lazy('index')


class SignUpView(BSModalCreateView):
    form_class = CustomUserCreationForm
    template_name = 'examples/signup.html'
    success_message = 'Success: Sign up succeeded. You can now Log in.'
    success_url = reverse_lazy('index')


class CustomLoginView(BSModalLoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'examples/login.html'
    success_message = 'Success: You were successfully logged in.'
    success_url = reverse_lazy('index')


def books(request):
    data = dict()
    if request.method == 'GET':
        books = Book.objects.all()
        data['table'] = render_to_string(
            '_books_table.html',
            {'books': books},
            request=request
        )
        return JsonResponse(data)

templates/_books_table.html
<table id="books-table" class="table">
  <thead>
  <tr>
    <th class="text-center" scope="col">#</th>
    <th class="text-center" scope="col">Title</th>
    <th class="text-center" scope="col">Author</th>
    <th class="text-center" scope="col">Type</th>
    <th class="text-center" scope="col">Publication date</th>
    <th class="text-center" scope="col">Pages</th>
    <th class="text-center" scope="col">Price (€)</th>
    <th class="text-center" scope="col">Read / Update / Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for book in books %}
    <tr>
      <th class="text-center" scope="row">{{ forloop.counter }}</th>
      <td class="text-center">{{ book.title }}</td>
      <td class="text-center">{{ book.author }}</td>
      <td class="text-center">{{ book.get_book_type_display }}</td>
      <td class="text-center">{{ book.publication_date }}</td>
      <td class="text-center">{{ book.pages }}</td>
      <td class="text-center">{{ book.price }}</td>
      <td class="text-center">
        <!-- Read book buttons -->
        <button type="button" class="bs-modal read-book btn btn-sm btn-primary" data-form-url="{% url 'read_book' book.pk %}">
          <span class="fa fa-eye"></span>
        </button>
        <!-- Update book buttons -->
        <button type="button" class="update-book btn btn-sm btn-primary" data-form-url="{% url 'update_book' book.pk %}">
          <span class="fa fa-pencil"></span>
        </button>
        <!-- Delete book buttons -->
        <button type="button" class="bs-modal delete-book btn btn-sm btn-danger" data-form-url="{% url 'delete_book' book.pk %}">
          <span class="fa fa-trash"></span>
        </button>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

templates/_footer.html
<footer class="footer" style="border-top: 1px solid #eee;">
  <div class="container">
    <p class="text-muted mt-3">&copy; Все права защищены Аней.
    </p>
  </div>
</footer>

templates/_header.html
{% load static %}


<header style="border-bottom: 1px solid #eee;">

    <!-- Messages -->
    <div>
        {% if messages %}
            {% for message in messages %}
                <div style="border-radius:0;" {% if message.tags %}
                     class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0"
                     role="alert" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <!-- End Messages -->

    <nav class="navbar navbar-light navbar-expand-md bg-white navbar-clean">
        <div class="container">

            <!-- Кнопка меню для мобил -->
            <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler">
                <span class="sr-only">Панель навигации</span>
                <span class="navbar-toggler-icon"></span></button>

            <!-- Логотип -->
            <a class="navbar-brand" href="/">
                <img src="/static/assets/img/logo.png" alt="Anya'School" width="250px">
            </a>
            <!-- Сворачивающиеся пункты меню -->
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav mx-auto">
                    <li role="presentation" class="nav-item"><a class="nav-link active" href="{% url 'index' %}">Домой</a></li>
                    <li role="presentation" class="nav-item"><a class="nav-link" href="{% url 'about' %}">О нас</a></li>
                    <li role="presentation" class="nav-item"><a class="nav-link" href="#">Цены</a></li>
                </ul>

                <ul class="nav navbar-nav mx-auto">
                    {% if not user.is_anonymous %}
                        <li role="presentation" class="nav-item">
                            <span>Вы зашли как<strong> {{ user }}</strong>.</span>
                            <a href="{% url 'logout' %}" id="logout-btn" class="btn btn-danger" role="button">Выйти</a>
                        </li>
                    {% else %}
                        <li role="presentation" class="nav-item mr-2 my-2">
                            <button id="signup-btn" class="btn btn-secondary " type="button" name="button">
                                Начать бесплатно
                            </button>
                        </li>
                        <li role="presentation" class="nav-item">

                            <button id="login-btn" class="btn btn-primary my-2" type="button" name="button">Войти
                            </button>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </nav>
</header>

{#<!-- Header -->#}
{#<header style="border-bottom: 1px solid #eee;">#}
{#    <!-- Messages -->#}
{#    <div>#}
{#        {% if messages %}#}
{#            {% for message in messages %}#}
{#                <div style="border-radius:0;" {% if message.tags %}#}
{#                     class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0"#}
{#                     role="alert" {% endif %}>#}
{#                    {{ message }}#}
{#                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                        <span aria-hidden="true">&times;</span>#}
{#                    </button>#}
{#                </div>#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#    </div>#}
{#    <!-- End Messages -->#}
{##}
{#    <div class="container">#}
{#        <!-- Navbar -->#}
{#        <!-- Important: columns can be used directly in navbar since it is d-flex -->#}
{#        <nav class="navbar navbar-expand-md navbar-light clean-navbar">#}
{##}
{##}
{#            <!-- Логотип -->#}
{#            <div class="container">#}
{#                <a class="navbar-brand" href="/">#}
{#                    <img src="/static/assets/img/logo.png" alt="Anya'School" width="80%">#}
{#                </a>#}
{##}
{#                <!-- Кнопка меню для мобил -->#}
{#                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"#}
{#                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">#}
{#                    <span class="navbar-toggler-icon"></span>#}
{#                </button>#}
{##}
{#                <!-- Сворачивающиеся пункты меню -->#}
{#                <div class="collapse navbar-collapse" id="navbarNav">#}
{#                    <ul class="nav navbar-nav ml-auto">#}
{#                        <li role="presentation" class="nav-item active"><a class="nav-link active" href="#">Home</a></li>#}
{#                        <li role="presentation" class="nav-item"><a class="nav-link" href="#">Features</a></li>#}
{#                        <li role="presentation" class="nav-item"><a class="nav-link" href="#">Pricing</a></li>#}
{#                        <li role="presentation" class="nav-item"><a class="nav-link" href="#">Payment</a></li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="row">#}
{#                    <div class="col-12 mb-3">#}
{#                        {% if not user.is_anonymous %}#}
{#                            <span>#}
{#                Вы зашли как#}
{#                <strong>{{ user }}</strong>.#}
{#              </span>#}
{#                            <a href="{% url 'logout' %}" id="logout-btn" class="btn btn-danger"#}
{#                               role="button">Выйти</a>#}
{#                        {% else %}#}
{#                            <div class="col-12 mb-3">#}
{#                                <button id="signup-btn" class="btn btn-secondary" type="button" name="button">#}
{#                                    Начать бесплатно#}
{#                                </button>#}
{#                            </div>#}
{#                            <button id="login-btn" class="btn btn-primary" type="button" name="button">Войти#}
{#                            </button>#}
{#                        {% endif %}#}
{#                    </div>#}
{#                </div>#}
{#        </nav>#}
{#        <!-- End Navbar -->#}
{#    </div>#}
{#</header>#}
{#<!-- End Header -->#}

templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

templates/about.html
{% extends 'base.html' %}

{% block title %}
    О нас
{% endblock title %}

{% block content %}

  {% include "_modal.html" %}

  <div class="container mt-3">
    <div class="row">
      <div class="col">

        <h4>
          <strong>О нас</strong>
        </h4>
        <p>Create, Read, Update and Delete books in Bootstrap modal.</p>

        <div class="row">
          <div class="col-12 mb-3">
            <button id="create-book-sync" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create book - Synchronous
            </button>
            <button id="create-book-async" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create book - Asynchronous
            </button>
            <button id="filter-book" class="bs-modal btn btn-primary" type="button" name="button" data-form-url="{% url 'filter_book' %}">
              <span class="fa fa-filter mr-2"></span>Filter books
            </button>
          </div>
          <div class="col-12 mb-3">
            {% if books %}
              {% include "_books_table.html" %}
            {% else %}
              <p class="no-books text-primary">No books added yet.</p>
            {% endif %}
          </div>
        </div>

      <h4>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br>AAAAAA<br></h4>


      </div>
    </div>
  </div>

{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
          // Log in & Sign up buttons
          // The formURL is given explicitly
          $("#login-btn").modalForm({
            formURL: "{% url 'login' %}"
          });

          $("#signup-btn").modalForm({
            formURL: "{% url 'signup' %}"
          });

          // Create book button opens modal with id="create-modal"
          /* 
          $("#create-book").modalForm({
            formURL: "{% url 'create_book' %}",
            modalID: "#create-modal"
          });
          */

          function createBookSyncModalForm() {
            $("#create-book-sync").modalForm({
                formURL: "{% url 'create_book' %}",
                modalID: "#create-modal"
            });
          }
          createBookSyncModalForm();

          var asyncSuccessMessageCreate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was created.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          function updateBookModalForm() {
            $(".update-book").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "books/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: updateBookModalForm
                }
              });
            });
          }
          updateBookModalForm();

          function createBookAsyncModalForm() {
            $("#create-book-async").modalForm({
                formURL: "{% url 'create_book' %}",
                modalID: "#create-modal",
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: true,
                  successMessage: asyncSuccessMessageCreate,
                  dataUrl: "books/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: updateBookModalForm
                }
            });
          }
          createBookAsyncModalForm();

          // Read and Delete book buttons open modal with id="modal"
          // The formURL is retrieved from the data of the element
          $(".bs-modal").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });

          // Hide message
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <!-- Font awesome CSS -->
        <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <!-- Custom CSS -->
        <style media="screen">
            .invalid {
                color: #dc3545;
                font-size: 80%;
            }

            body {
                display: flex;
                flex-direction: column;
                min-height: 100vh;
            }

            .footer {
                margin: auto 0 0;
                height: 56px;
            }
        </style>
    {% endblock stylesheets %}

    <link rel="icon" href="{% static '/img/favicon.png' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>

<!-- Includes -->
{% include "_header.html" %}

{% block content %}{% endblock content %}

<!-- Includes -->
{% include "_footer.html" %}

<!-- JavaScript -->
{% block scripts %}
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
{% endblock scripts %}

{% block extrascripts %}{% endblock extrascripts %}

</body>

</html>

templates/examples/create_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

templates/examples/delete_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete book with title
      <strong>{{ book.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/examples/filter_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Filter Books</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>


  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <input type="submit" class="btn btn-primary" name="clear" value="Clear"/>
    <button type="button" class="submit-btn btn btn-primary">Filter</button>
  </div>

</form>

templates/examples/login.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Log in</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary" formnovalidate="formnovalidate">Log in</button>
  </div>

</form>

templates/examples/read_book.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Book details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    Title:
    {{ book.title }}
  </div>
  <div class="">
    Author:
    {{ book.author }}
  </div>
  <div class="">
    Price:
    {{ book.price }}
    €
  </div>
  <div class="">
    Pages:
    {{ book.pages }}
  </div>
  <div class="">
    Type:
    {{ book.get_book_type_display }}
  </div>
  <div class="">
    Publication date:
    {{ book.publication_date }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

templates/examples/signup.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Sign up</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary" formnovalidate="formnovalidate">Sign up</button>
  </div>

</form>

templates/examples/update_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Update</button>
  </div>

</form>